version: '3.8'
services:
  postgres:
    image: postgres:16.3
    container_name: bancodb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    networks:
      - banco-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - banco-network

networks:
  banco-network:
    driver: bridge
